name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main # Run the workflow when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Step 3: Build the application
    - name: Build Spring Boot App
      run: mvn clean install